import './globals.css'
import type { Metadata } from 'next'
import Navbar from "@/components/navbar/page";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main className="min-h-screen container mx-auto px-4 h-full">
          {children}
        </main>
      </body>
    </html>
  )
}
